/**
 * Component Registry — Central tracking for workflow-generated components
 *
 * Workflows can create buttons, select menus, modals, etc. This registry tracks:
 *   - Button custom IDs → workflow/block info
 *   - Select menu custom IDs → workflow/block info
 *   - Modal custom IDs → workflow/block info
 *
 * This allows us to route interactions back to the correct workflow block.
 *
 * Component ID format: `wf:<workflowId>:<blockId>:<componentType>:<payload>`
 * e.g., `wf:507f1f77bcf86cd799439011:blk_12345:button:action_0`
 *
 * Storage: in-memory Map during execution, can be extended to database for persistence
 */

class ComponentRegistry {
  constructor() {
    // Map<customId, { workflowId, blockId, type, actionData }>
    this.components = new Map();
    this.maxAge = 24 * 60 * 60 * 1000; // 24 hours TTL
    this.cleanup = this._scheduleCleanup();
  }

  /**
   * Register a component generated by a workflow block
   * @param {string} customId - Discord component custom ID
   * @param {object} meta - { workflowId, blockId, type, actionData, expiresAt }
   */
  register(customId, meta) {
    if (!customId || !meta.workflowId || !meta.blockId) {
      console.warn('[ComponentRegistry] Invalid registration:', { customId, meta });
      return false;
    }

    meta.expiresAt = Date.now() + this.maxAge;
    this.components.set(customId, meta);
    return true;
  }

  /**
   * Resolve a component to its workflow metadata
   * @param {string} customId - Discord component custom ID
   * @returns {object|null} Metadata or null if not found/expired
   */
  resolve(customId) {
    const meta = this.components.get(customId);
    if (!meta) return null;

    if (meta.expiresAt && Date.now() > meta.expiresAt) {
      this.components.delete(customId);
      return null;
    }

    return meta;
  }

  /**
   * Get all components for a workflow
   * @param {string} workflowId
   * @returns {object[]} Array of component metadata
   */
  getWorkflowComponents(workflowId) {
    return Array.from(this.components.values())
      .filter((m) => m.workflowId === workflowId);
  }

  /**
   * Get all components for a block
   * @param {string} workflowId
   * @param {string} blockId
   * @returns {object[]} Array of component metadata
   */
  getBlockComponents(workflowId, blockId) {
    return Array.from(this.components.values())
      .filter((m) => m.workflowId === workflowId && m.blockId === blockId);
  }

  /**
   * Deregister (remove) a component
   * @param {string} customId
   */
  deregister(customId) {
    this.components.delete(customId);
  }

  /**
   * Clean up expired components
   * @private
   */
  _cleanup() {
    const now = Date.now();
    let removed = 0;
    for (const [customId, meta] of this.components.entries()) {
      if (meta.expiresAt && now > meta.expiresAt) {
        this.components.delete(customId);
        removed++;
      }
    }
    if (removed > 0) {
      console.log(`[ComponentRegistry] Cleaned up ${removed} expired components`);
    }
  }

  /**
   * Schedule periodic cleanup
   * @private
   */
  _scheduleCleanup() {
    return setInterval(() => this._cleanup(), 60 * 60 * 1000); // Every hour
  }

  /**
   * Shutdown the registry
   */
  destroy() {
    if (this.cleanup) clearInterval(this.cleanup);
    this.components.clear();
  }

  /**
   * Get registry stats (for debugging)
   */
  getStats() {
    return {
      totalComponents: this.components.size,
      byType: {
        button: Array.from(this.components.values()).filter((m) => m.type === 'button').length,
        selectMenu: Array.from(this.components.values()).filter((m) => m.type === 'selectMenu').length,
        modal: Array.from(this.components.values()).filter((m) => m.type === 'modal').length,
      },
    };
  }
}

// Singleton instance
let instance = null;

function getComponentRegistry() {
  if (!instance) {
    instance = new ComponentRegistry();
  }
  return instance;
}

module.exports = {
  ComponentRegistry,
  getComponentRegistry,
};
